config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :quotations
  resources :currencies

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'home#index'
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :currency

  INTERVALS = {
    'day': {date_interval: 1.day, date_format: "%H", maxLabels: 6},
    'week': { date_interval: 7.day, date_format: "%b/%d", maxLabels: 7},
    'month': { date_interval: 1.month, date_format: "%b/%d", maxLabels: 15},
    'months': { date_interval: 3.month, date_format: "%b", maxLabels: 3},
    'year': { date_interval: 1.year, date_format: "%b/%y", maxLabels: 12}
  }

  def self.get_date_interval(interval)
    INTERVALS[interval.to_sym][:date_interval]
  end

  def self.json_serialize(rows, interval)
    puts "interval #{interval}"
    data = []
    labels = []
    interval_config = INTERVALS[interval.to_sym]
    rows.each do |obj|
      values = {
        bid_value: obj.bid_value.to_f,
        ask_value: obj.ask_value.to_f,
        date: obj.date.strftime("%Y-%m-%d %H:%M")
      }
      labels.push(obj.date.strftime(interval_config[:date_format]))
      data.push(values)
    end
    return {data: data, labels: labels, maxLabels: interval_config[:maxLabels]}.to_json
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  skip_before_action :require_login, :if => :format_json?
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  def format_json?
    request.format.json?
  end

  # GET /quotations
  # GET /quotations.json
  def index
    puts params
    currency = params["currrency"]
    interval = params["interval"] || 'day'
    interval = interval.downcase
    interval = 'day' if not Quotation::INTERVALS.keys.include? interval.to_sym

    @quotations = Quotation.all.order("currency_id asc, date asc")
    puts "currency #{currency}"
    puts currency.present?
    if currency.present?
      currency = Currency.find_by(code: currency)
      start_day = Date.today - Quotation.get_date_interval(interval)
      puts start_day
      @quotations = @quotations.where(
        currency: currency,
        interval: interval
      ).where("date >= ?", start_day)
      .order("date asc")
    end
    if request.format != 'application/json'
      page_limit = params.fetch(:limit, 20)
      @quotations = @quotations.paginate(page: params[:page], per_page: page_limit)
    end
    respond_to do |format|
      format.html
      format.json do
        render json: Quotation.json_serialize(@quotations, interval)
      end
    end
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:currency_id, :bid_value, :ask_value, :max_bid, :min_bid, :variation_bid, :open_bid_value, :date, :created_at, :updated_at)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<%= form_with(model: quotation, local: true) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.text_field :currency_id %>
  </div>

  <div class="field">
    <%= form.label :bid_value %>
    <%= form.text_field :bid_value %>
  </div>

  <div class="field">
    <%= form.label :ask_value %>
    <%= form.text_field :ask_value %>
  </div>

  <div class="field">
    <%= form.label :max_bid %>
    <%= form.text_field :max_bid %>
  </div>

  <div class="field">
    <%= form.label :min_bid %>
    <%= form.text_field :min_bid %>
  </div>

  <div class="field">
    <%= form.label :variation_bid %>
    <%= form.text_field :variation_bid %>
  </div>

  <div class="field">
    <%= form.label :open_bid_value %>
    <%= form.text_field :open_bid_value %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<style>
.pagination{
  margin-top: 20px;
}
.pagination a, .pagination span, .pagination em {
    position: relative;
    display: block;
    padding: .5rem .75rem;
    margin-left: -1px;
    line-height: 1.25;
    color: #007bff;
    background-color: #fff;
    border: 1px solid #dee2e6;
}
</style>

<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<%= link_to 'New Quotation', new_quotation_path %>


<table>
  <thead>
    <tr>
      <th>Interval</th>
      <th>Currency</th>
      <th>Bid value</th>
      <th>Ask value</th>
      <th>Max bid</th>
      <th>Min bid</th>
      <th>Variation bid</th>
      <th>Open bid value</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.interval %></td>
        <td><%= quotation.currency&.code %></td>
        <td><%= quotation.bid_value %></td>
        <td><%= quotation.ask_value %></td>
        <td><%= quotation.max_bid %></td>
        <td><%= quotation.min_bid %></td>
        <td><%= quotation.variation_bid %></td>
        <td><%= quotation.open_bid_value %></td>
        <td><%= quotation.date %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @quotations  %>
<br>

app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @quotation.currency %>
</p>

<p>
  <strong>Bid value:</strong>
  <%= @quotation.bid_value %>
</p>

<p>
  <strong>Ask value:</strong>
  <%= @quotation.ask_value %>
</p>

<p>
  <strong>Max bid:</strong>
  <%= @quotation.max_bid %>
</p>

<p>
  <strong>Min bid:</strong>
  <%= @quotation.min_bid %>
</p>

<p>
  <strong>Variation bid:</strong>
  <%= @quotation.variation_bid %>
</p>

<p>
  <strong>Open bid value:</strong>
  <%= @quotation.open_bid_value %>
</p>

<p>
  <strong>Date:</strong>
  <%= @quotation.date %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @quotation.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @quotation.updated_at %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>